version: '3.8'

services:
  # Data Pipeline Service
  data-pipeline:
    build:
      context: ../
      dockerfile: docker/data-pipeline/Dockerfile
    container_name: fashion-data-pipeline
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ../data:/app/data
      - ../backend:/app/backend
    working_dir: /app/backend/data-pipeline
    networks:
      - fashion-network
    
  # Search API Service
  search-api:
    build:
      context: ../
      dockerfile: docker/search-api/Dockerfile
    container_name: fashion-search-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ../data:/app/data
      - ../backend:/app/backend
    working_dir: /app/backend/search-api
    depends_on:
      - data-pipeline
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fashion-network
    


networks:
  fashion-network:
    driver: bridge 

volumes:
  data:
    driver: local 